development:
  slack_incoming_webhook: <%= ENV["SLACK_WEBHOOK_URL"] %>
  slack_app_token: <%= ENV["SLACK_APP_TOKEN"] %>
  slack_email_override: rewards
  slack_channel_prefix: dev_

test:
  slack_incoming_webhook: https://slack.com
  slack_app_token: xoxp-abcd123
  slack_email_override: rewards
  slack_channel_prefix: test_

production:
  slack_incoming_webhook: <%= ENV["SLACK_WEBHOOK_URL"] %>
  slack_app_token: <%= ENV["SLACK_APP_TOKEN"] %>
  slack_email_override: rewards
  slack_channel_prefix: dev_
