development:
  slack_incoming_webhook: https://hooks.slack.com/services/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
  slack_app_token: xoxb-322901699254-2002385917043-H8Y9KUXvXWLOVk2KI5LYWp79
  slack_email_override: rewards
  slack_channel_prefix: dev_

test:
  slack_incoming_webhook: https://slack.com
  slack_app_token: xoxp-abcd123
  slack_email_override: rewards
  slack_channel_prefix: test_

production:
  slack_incoming_webhook: https://hooks.slack.com/services/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
  slack_app_token: xoxb-322901699254-2002385917043-H8Y9KUXvXWLOVk2KI5LYWp79
  slack_email_override: rewards
  slack_channel_prefix:
